### ISSUE TITLE
Pull requests not being processed?

### ISSUE THREAD

**Issue by BKirev** [abhpd/hacktoberfest2021#270]
Hey there,

I was wondering if the pull requests that are in 'queue' will be processed, since I guess there are other people like me that are 3/4 for Hacktoberfest and counting on this repo.

If I can help in any way, I'll happily do that.

Regards!

**Comment by abhpd** [comment]
@BKirev We're up for a new season, this time we might need more maintainers as we weren't expecting that many PRs last time. Let me know if you would still like to help. Thanks.
