### ISSUE TITLE
Tower of hanoi

### ISSUE THREAD

**Issue by meghna750** [abhpd/hacktoberfest2021#335]
Hello @abhpd ,
I hope you are going very well. I am participating in hacktoberfest 2021 and want to add the concept of "TOWER-OF-HANOI" in your repo in C++ algorithms section. This problem is a well-known example of how recursion is implemented. I will solve it by writing simple code which will be well commented and justified. I will make sure that the reader understands each and every line of my code.
Please assign this issue to me.
Thanks.

**Comment by abhpd** [comment]
@meghna750 You can open a PR. No need to get assigned to a task.
