### ISSUE TITLE
HacktoberFest website says excluded project?

### ISSUE THREAD

**Issue by m-prth** [abhpd/hacktoberfest2021#612]

**Comment by VibhuGautam** [comment]
Yes it also says in my contribution list also. 
Will it be counted or not ?

**Comment by m-prth** [comment]
Lets hope that it gets counted

**Comment by swaraj-ssk** [comment]
The project is excluded now.

**Comment by VibhuGautam** [comment]
I don't think so it will get counted

**Comment by meghna750** [comment]
Actually, Hacktoberfest has excluded many DSA repositories, which is why our contribution is not counted in it :(.

**Comment by abhpd** [comment]
I'm receiving this from almost everywhere. I have contacted them regarding this. I will let you guys know as soon as I get any reply back.
