### ISSUE TITLE
excluded project

### ISSUE THREAD

**Issue by JI-10** [abhpd/hacktoberfest2021#638]
The hactoberFest website says project excluded . what does it mean?

**Comment by SamikshyaMstar** [comment]
Exactly this is the issue I am facing. Even if I got my PR merged, my total progress is 0.

**Comment by Sun-0321** [comment]
Yeah.Even I received the same.

**Comment by abhpd** [comment]
@SamikshyaMstar @JI-10 They seem to have excluded most of the DSA based Repositories. I have contacted them for a clearer answer.
